[build]
builder = "nixpacks"

[build.env]
NIXPACKS_PYTHON_VERSION = "3.11"
NODE_VERSION = "18"

[build.command]
cmd = "npm install --prefix client && npm run build --prefix client"

[deploy]
startCommand = "python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
